import gorilla
import argparse
import os
import sys
from contextlib import contextmanager
from typing import Any, Dict, Optional, Union

from PIL import Image
import os.path as osp
import numpy as np
import random
import importlib
import json

import torch
import torchvision.transforms as transforms
import cv2

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.join(BASE_DIR, '..', 'Pose_Estimation_Model')
sys.path.append(os.path.join(ROOT_DIR, 'provider'))
sys.path.append(os.path.join(ROOT_DIR, 'utils'))
sys.path.append(os.path.join(ROOT_DIR, 'model'))
sys.path.append(os.path.join(BASE_DIR, 'model', 'pointnet2'))

_DEFAULT_MODEL_NAME = "pose_estimation_model"
_DEFAULT_CONFIG_PATH = osp.join(BASE_DIR, "config", "base.yaml")
_DEFAULT_CHECKPOINT_PATH = osp.join(BASE_DIR, "checkpoints", "sam-6d-pem-base.pth")

# Cache the default model for optional preloading / fast subsequent calls.
_CACHED_DEFAULT_MODEL = None
_CACHED_DEFAULT_MODEL_KEY: Optional[tuple] = None


@contextmanager
def _cwd(path: str):
    prev = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(prev)


def get_parser():
    parser = argparse.ArgumentParser(
        description="Pose Estimation")
    # pem
    parser.add_argument("--gpus",
                        type=str,
                        default="0",
                        help="path to pretrain model")
    parser.add_argument("--model",
                        type=str,
                        default="pose_estimation_model",
                        help="path to model file")
    parser.add_argument("--config",
                        type=str,
                        default="config/base.yaml",
                        help="path to config file, different config.yaml use different config")
    parser.add_argument("--iter",
                        type=int,
                        default=600000,
                        help="epoch num. for testing")
    parser.add_argument("--exp_id",
                        type=int,
                        default=0,
                        help="")
    
    # input
    parser.add_argument("--output_dir", nargs="?", help="Path to root directory of the output")
    parser.add_argument("--cad_path", nargs="?", help="Path to CAD(mm)")
    parser.add_argument("--rgb_path", nargs="?", help="Path to RGB image")
    parser.add_argument("--depth_path", nargs="?", help="Path to Depth image(mm)")
    parser.add_argument("--cam_path", nargs="?", help="Path to camera information")
    parser.add_argument("--seg_path", nargs="?", help="Path to segmentation information(generated by ISM)")
    parser.add_argument("--det_score_thresh", default=0.2, help="The score threshold of detection")
    args_cfg = parser.parse_args()

    return args_cfg


def build_inference_cfg(
    output_dir: str,
    cad_path: str,
    rgb_path: str,
    depth_path: str,
    cam_path: str,
    seg_path: str,
    det_score_thresh: float = 0.2,
    gpus: str = "0",
    model_name: str = "pose_estimation_model",
    config_path: Optional[str] = None,
    iter_: int = 600000,
    exp_id: int = 0,
):
    """Build gorilla config for PEM inference (CLI-free)."""
    if config_path is None:
        config_path = osp.join(BASE_DIR, "config", "base.yaml")
    elif not osp.isabs(config_path):
        config_path = osp.join(BASE_DIR, config_path)

    cfg = gorilla.Config.fromfile(config_path)
    exp_name = (
        model_name
        + "_"
        + osp.splitext(osp.basename(config_path))[0]
        + "_id"
        + str(exp_id)
    )
    log_dir = osp.join("log", exp_name)

    cfg.exp_name = exp_name
    cfg.gpus = gpus
    cfg.model_name = model_name
    cfg.log_dir = log_dir
    cfg.test_iter = iter_

    cfg.output_dir = output_dir
    cfg.cad_path = cad_path
    cfg.rgb_path = rgb_path
    cfg.depth_path = depth_path
    cfg.cam_path = cam_path
    cfg.seg_path = seg_path

    cfg.det_score_thresh = det_score_thresh
    gorilla.utils.set_cuda_visible_devices(gpu_ids=cfg.gpus)

    return cfg


def preload_default_pem_model(
    *,
    gpus: str = "0",
    model_name: str = _DEFAULT_MODEL_NAME,
    checkpoint_path: Optional[str] = None,
    config_path: Optional[str] = None,
    verbose: bool = True,
) -> None:
    """
    Preload PEM model weights (network + checkpoint) into current process.

    This is intended for fail-fast startup: if CUDA/checkpoints/deps are broken,
    importing this module (or calling this function) will raise early.

    Notes:
    - This only preloads the model; it does NOT extract templates or run forward.
    - Uses ``Pose_Estimation_Model`` as cwd so relative checkpoints work.
    """
    global _CACHED_DEFAULT_MODEL, _CACHED_DEFAULT_MODEL_KEY

    if model_name != _DEFAULT_MODEL_NAME:
        raise ValueError(
            f"preload_default_pem_model only supports model_name='{_DEFAULT_MODEL_NAME}', got '{model_name}'"
        )

    if config_path is None:
        config_path = _DEFAULT_CONFIG_PATH
    if checkpoint_path is None:
        checkpoint_path = _DEFAULT_CHECKPOINT_PATH

    resolved_config_path = osp.abspath(config_path)
    resolved_ckpt_path = osp.abspath(checkpoint_path)
    cache_key = (gpus, model_name, resolved_ckpt_path, resolved_config_path)
    if _CACHED_DEFAULT_MODEL is not None and _CACHED_DEFAULT_MODEL_KEY == cache_key:
        if verbose:
            print(f"=> [preload] skip (cache hit): key={cache_key}")
        return

    # Make CUDA_VISIBLE_DEVICES match the caller's gpus setting.
    gorilla.utils.set_cuda_visible_devices(gpu_ids=gpus)

    if verbose:
        try:
            print("=> [preload] env")
            print(f"   SAM6D_CUDA_VISIBLE_DEVICES={os.environ.get('SAM6D_CUDA_VISIBLE_DEVICES')}")
            print(f"   PYTORCH_CUDA_ALLOC_CONF={os.environ.get('PYTORCH_CUDA_ALLOC_CONF')}")
            print(f"=> [preload] config_path: {resolved_config_path}")
            print(f"=> [preload] checkpoint_path: {resolved_ckpt_path}")
            print(f"=> [preload] cache_key: {cache_key}")
            print("=> [preload] torch info")
            print(f"   torch_version={torch.__version__}")
            print(f"   cuda_version={torch.version.cuda}")
            print(f"   cuda_is_available={torch.cuda.is_available()}")
            if torch.cuda.is_available():
                torch.cuda.synchronize()
                dev = torch.cuda.current_device()
                props = torch.cuda.get_device_properties(dev)
                alloc_gb = torch.cuda.memory_allocated(dev) / (1024**3)
                reserved_gb = torch.cuda.memory_reserved(dev) / (1024**3)
                print(f"   current_device={dev}")
                print(f"   device_name={props.name}")
                print(f"   mem_allocated_GiB={alloc_gb:.3f}")
                print(f"   mem_reserved_GiB={reserved_gb:.3f}")
        except Exception as exc:
            print(f"=> [preload] (warn) failed to print env/torch info: {exc}")

    with _cwd(BASE_DIR):
        try:
            if verbose:
                print(f"=> [preload] creating model (model={model_name}) ...")
            cfg = gorilla.Config.fromfile(resolved_config_path)
            cfg.model_name = model_name
            cfg.gpus = gpus

            if verbose:
                print("=> [preload] importing model module ...")
            MODEL = importlib.import_module(cfg.model_name)
            model = MODEL.Net(cfg.model)
            model = model.cuda()
            model.eval()

            if verbose:
                print(f"=> [preload] loading checkpoint: {resolved_ckpt_path}")
            gorilla.solver.load_checkpoint(model=model, filename=resolved_ckpt_path)

            if verbose and torch.cuda.is_available():
                torch.cuda.synchronize()
                dev = torch.cuda.current_device()
                alloc_gb = torch.cuda.memory_allocated(dev) / (1024**3)
                reserved_gb = torch.cuda.memory_reserved(dev) / (1024**3)
                print(f"=> [preload] done. mem_allocated_GiB={alloc_gb:.3f} mem_reserved_GiB={reserved_gb:.3f}")
        except Exception as exc:
            if verbose:
                print(f"=> [preload] failed: {type(exc).__name__}: {exc}")
            raise

    _CACHED_DEFAULT_MODEL = model
    _CACHED_DEFAULT_MODEL_KEY = cache_key


def _maybe_autopreload_default_pem() -> None:
    flag = os.environ.get("SAM6D_PEM_PRELOAD_DEFAULT", "1").strip().lower()
    if flag in {"0", "false", "no", "off"}:
        if os.environ.get("SAM6D_PEM_PRELOAD_VERBOSE", "0").strip().lower() in {"1", "true", "yes"}:
            print("=> [preload] disabled by SAM6D_PEM_PRELOAD_DEFAULT=0")
        return

    verbose = os.environ.get("SAM6D_PEM_PRELOAD_VERBOSE", "1").strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }
    gpus = os.environ.get("SAM6D_CUDA_VISIBLE_DEVICES", "0")
    if verbose:
        print(f"=> [preload] auto start (default) flag={flag} gpus={gpus}")
    preload_default_pem_model(gpus=gpus, verbose=verbose)


_maybe_autopreload_default_pem()


def init():
    args = get_parser()
    return build_inference_cfg(
        output_dir=args.output_dir,
        cad_path=args.cad_path,
        rgb_path=args.rgb_path,
        depth_path=args.depth_path,
        cam_path=args.cam_path,
        seg_path=args.seg_path,
        det_score_thresh=float(args.det_score_thresh),
        gpus=args.gpus,
        model_name=args.model,
        config_path=(
            args.config
            if osp.isabs(args.config)
            else osp.join(BASE_DIR, args.config)
        ),
        iter_=args.iter,
        exp_id=args.exp_id,
    )



from data_utils import (
    load_im,
    get_bbox,
    get_point_cloud_from_depth,
    get_resize_rgb_choose,
)
from draw_utils import draw_detections
import pycocotools.mask as cocomask
import trimesh

rgb_transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                                    std=[0.229, 0.224, 0.225])])

def visualize(rgb, pred_rot, pred_trans, model_points, K, save_path):
    img = draw_detections(rgb, pred_rot, pred_trans, model_points, K, color=(255, 0, 0))
    img = Image.fromarray(np.uint8(img))
    img.save(save_path)
    prediction = Image.open(save_path)
    
    # concat side by side in PIL
    rgb = Image.fromarray(np.uint8(rgb))
    img = np.array(img)
    concat = Image.new('RGB', (img.shape[1] + prediction.size[0], img.shape[0]))
    concat.paste(rgb, (0, 0))
    concat.paste(prediction, (img.shape[1], 0))
    return concat


def _get_template(path, cfg, tem_index=1):
    rgb_path = os.path.join(path, 'rgb_'+str(tem_index)+'.png')
    mask_path = os.path.join(path, 'mask_'+str(tem_index)+'.png')
    xyz_path = os.path.join(path, 'xyz_'+str(tem_index)+'.npy')

    rgb = load_im(rgb_path).astype(np.uint8)
    xyz = np.load(xyz_path).astype(np.float32) / 1000.0  
    mask = load_im(mask_path).astype(np.uint8) == 255

    bbox = get_bbox(mask)
    y1, y2, x1, x2 = bbox
    mask = mask[y1:y2, x1:x2]

    rgb = rgb[:,:,::-1][y1:y2, x1:x2, :]
    if cfg.rgb_mask_flag:
        rgb = rgb * (mask[:,:,None]>0).astype(np.uint8)

    rgb = cv2.resize(rgb, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_LINEAR)
    rgb = rgb_transform(np.array(rgb))

    choose = (mask>0).astype(np.float32).flatten().nonzero()[0]
    if len(choose) <= cfg.n_sample_template_point:
        choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_template_point)
    else:
        choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_template_point, replace=False)
    choose = choose[choose_idx]
    xyz = xyz[y1:y2, x1:x2, :].reshape((-1, 3))[choose, :]

    rgb_choose = get_resize_rgb_choose(choose, [y1, y2, x1, x2], cfg.img_size)
    return rgb, rgb_choose, xyz


def get_templates(path, cfg):
    n_template_view = cfg.n_template_view
    all_tem = []
    all_tem_choose = []
    all_tem_pts = []

    total_nView = 42
    for v in range(n_template_view):
        i = int(total_nView / n_template_view * v)
        tem, tem_choose, tem_pts = _get_template(path, cfg, i)
        all_tem.append(torch.FloatTensor(tem).unsqueeze(0).cuda())
        all_tem_choose.append(torch.IntTensor(tem_choose).long().unsqueeze(0).cuda())
        all_tem_pts.append(torch.FloatTensor(tem_pts).unsqueeze(0).cuda())
    return all_tem, all_tem_pts, all_tem_choose


def get_test_data(rgb_path, depth_path, cam_path, cad_path, seg_path, det_score_thresh, cfg):
    dets = []
    with open(seg_path) as f:
        dets_ = json.load(f) # keys: scene_id, image_id, category_id, bbox, score, segmentation
    for det in dets_:
        if det['score'] > det_score_thresh:
            dets.append(det)
    del dets_

    cam_info = json.load(open(cam_path))
    K = np.array(cam_info['cam_K']).reshape(3, 3)

    whole_image = load_im(rgb_path).astype(np.uint8)
    if len(whole_image.shape)==2:
        whole_image = np.concatenate([whole_image[:,:,None], whole_image[:,:,None], whole_image[:,:,None]], axis=2)
    whole_depth = load_im(depth_path).astype(np.float32) * cam_info['depth_scale'] / 1000.0
    whole_pts = get_point_cloud_from_depth(whole_depth, K)

    mesh = trimesh.load_mesh(cad_path)
    model_points = mesh.sample(cfg.n_sample_model_point).astype(np.float32) / 1000.0
    radius = np.max(np.linalg.norm(model_points, axis=1))


    all_rgb = []
    all_cloud = []
    all_rgb_choose = []
    all_score = []
    all_dets = []
    for inst in dets:
        seg = inst['segmentation']
        score = inst['score']

        # mask
        h,w = seg['size']
        try:
            rle = cocomask.frPyObjects(seg, h, w)
        except:
            rle = seg
        mask = cocomask.decode(rle)
        mask = np.logical_and(mask > 0, whole_depth > 0)
        if np.sum(mask) > 32:
            bbox = get_bbox(mask)
            y1, y2, x1, x2 = bbox
        else:
            continue
        mask = mask[y1:y2, x1:x2]
        choose = mask.astype(np.float32).flatten().nonzero()[0]

        # pts
        cloud = whole_pts.copy()[y1:y2, x1:x2, :].reshape(-1, 3)[choose, :]
        center = np.mean(cloud, axis=0)
        tmp_cloud = cloud - center[None, :]
        flag = np.linalg.norm(tmp_cloud, axis=1) < radius * 1.2
        if np.sum(flag) < 4:
            continue
        choose = choose[flag]
        cloud = cloud[flag]

        if len(choose) <= cfg.n_sample_observed_point:
            choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_observed_point)
        else:
            choose_idx = np.random.choice(np.arange(len(choose)), cfg.n_sample_observed_point, replace=False)
        choose = choose[choose_idx]
        cloud = cloud[choose_idx]

        # rgb
        rgb = whole_image.copy()[y1:y2, x1:x2, :][:,:,::-1]
        if cfg.rgb_mask_flag:
            rgb = rgb * (mask[:,:,None]>0).astype(np.uint8)
        rgb = cv2.resize(rgb, (cfg.img_size, cfg.img_size), interpolation=cv2.INTER_LINEAR)
        rgb = rgb_transform(np.array(rgb))
        rgb_choose = get_resize_rgb_choose(choose, [y1, y2, x1, x2], cfg.img_size)

        all_rgb.append(torch.FloatTensor(rgb))
        all_cloud.append(torch.FloatTensor(cloud))
        all_rgb_choose.append(torch.IntTensor(rgb_choose).long())
        all_score.append(score)
        all_dets.append(inst)

    ret_dict = {}
    ret_dict['pts'] = torch.stack(all_cloud).cuda()
    ret_dict['rgb'] = torch.stack(all_rgb).cuda()
    ret_dict['rgb_choose'] = torch.stack(all_rgb_choose).cuda()
    ret_dict['score'] = torch.FloatTensor(all_score).cuda()

    ninstance = ret_dict['pts'].size(0)
    ret_dict['model'] = torch.FloatTensor(model_points).unsqueeze(0).repeat(ninstance, 1, 1).cuda()
    ret_dict['K'] = torch.FloatTensor(K).unsqueeze(0).repeat(ninstance, 1, 1).cuda()
    return ret_dict, whole_image, whole_pts.reshape(-1, 3), model_points, all_dets


def run_pose_inference(
    output_dir: Union[str, os.PathLike],
    cad_path: Union[str, os.PathLike],
    rgb_path: Union[str, os.PathLike],
    depth_path: Union[str, os.PathLike],
    cam_path: Union[str, os.PathLike],
    seg_path: Union[str, os.PathLike],
    *,
    det_score_thresh: float = 0.2,
    gpus: str = "0",
    model_name: str = "pose_estimation_model",
    config_path: Optional[str] = None,
    checkpoint_path: Optional[str] = None,
    iter_: int = 600000,
    exp_id: int = 0,
    verbose: bool = True,
    save_visualization: bool = True,
) -> Dict[str, Any]:
    """
    Run PEM pose estimation (import-friendly API).

    Writes ``detection_pem.json`` and optionally ``vis_pem.png`` under
    ``{output_dir}/sam6d_results/``. Model loading uses ``Pose_Estimation_Model`` as cwd so
    relative ``checkpoints/`` paths resolve correctly even when the caller's cwd differs.
    """
    output_dir = os.fspath(output_dir)
    cad_path = os.fspath(cad_path)
    rgb_path = os.fspath(rgb_path)
    depth_path = os.fspath(depth_path)
    cam_path = os.fspath(cam_path)
    seg_path = os.fspath(seg_path)

    global _CACHED_DEFAULT_MODEL, _CACHED_DEFAULT_MODEL_KEY

    config_path_is_default = config_path is None
    checkpoint_path_is_default = checkpoint_path is None

    cfg = build_inference_cfg(
        output_dir=output_dir,
        cad_path=cad_path,
        rgb_path=rgb_path,
        depth_path=depth_path,
        cam_path=cam_path,
        seg_path=seg_path,
        det_score_thresh=det_score_thresh,
        gpus=gpus,
        model_name=model_name,
        config_path=config_path,
        iter_=iter_,
        exp_id=exp_id,
    )

    random.seed(cfg.rd_seed)
    torch.manual_seed(cfg.rd_seed)
    np.random.seed(cfg.rd_seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(cfg.rd_seed)

    if checkpoint_path is None:
        checkpoint_path = osp.join(BASE_DIR, "checkpoints", "sam-6d-pem-base.pth")
    else:
        checkpoint_path = os.fspath(checkpoint_path)

    def _log(msg: str) -> None:
        if verbose:
            print(msg)

    use_cached_default_model = (
        model_name == _DEFAULT_MODEL_NAME
        and config_path_is_default
        and checkpoint_path_is_default
        and _CACHED_DEFAULT_MODEL is not None
        and _CACHED_DEFAULT_MODEL_KEY == (gpus, model_name, osp.abspath(checkpoint_path), osp.abspath(_DEFAULT_CONFIG_PATH))
    )

    with _cwd(BASE_DIR):
        _log("=> creating model ...")
        if use_cached_default_model:
            model = _CACHED_DEFAULT_MODEL
        else:
            MODEL = importlib.import_module(cfg.model_name)
            model = MODEL.Net(cfg.model)
            model = model.cuda()
            model.eval()
            gorilla.solver.load_checkpoint(model=model, filename=checkpoint_path)

            # Populate cache only for default usage.
            if (
                model_name == _DEFAULT_MODEL_NAME
                and config_path_is_default
                and checkpoint_path_is_default
            ):
                _CACHED_DEFAULT_MODEL_KEY = (
                    gpus,
                    model_name,
                    osp.abspath(checkpoint_path),
                    osp.abspath(_DEFAULT_CONFIG_PATH),
                )
                _CACHED_DEFAULT_MODEL = model

        _log("=> extracting templates ...")
        tem_path = osp.join(cfg.output_dir, "templates")
        all_tem, all_tem_pts, all_tem_choose = get_templates(tem_path, cfg.test_dataset)
        with torch.no_grad():
            all_tem_pts, all_tem_feat = model.feature_extraction.get_obj_feats(
                all_tem, all_tem_pts, all_tem_choose
            )

        _log("=> loading input data ...")
        input_data, img, _whole_pts, model_points, detections = get_test_data(
            cfg.rgb_path,
            cfg.depth_path,
            cfg.cam_path,
            cfg.cad_path,
            cfg.seg_path,
            cfg.det_score_thresh,
            cfg.test_dataset,
        )
        ninstance = input_data["pts"].size(0)
        if ninstance == 0:
            raise RuntimeError(
                "No valid instances for PEM after filtering (seg scores / depth / geometry). "
                "Lower det_score_thresh or fix segmentation."
            )

        _log("=> running model ...")
        with torch.no_grad():
            input_data["dense_po"] = all_tem_pts.repeat(ninstance, 1, 1)
            input_data["dense_fo"] = all_tem_feat.repeat(ninstance, 1, 1)
            out = model(input_data)

    if "pred_pose_score" in out.keys():
        pose_scores = out["pred_pose_score"] * out["score"]
    else:
        pose_scores = out["score"]
    pose_scores_np = pose_scores.detach().cpu().numpy()
    pred_rot = out["pred_R"].detach().cpu().numpy()
    pred_trans = out["pred_t"].detach().cpu().numpy() * 1000

    _log("=> saving results ...")
    os.makedirs(f"{cfg.output_dir}/sam6d_results", exist_ok=True)
    for idx, det in enumerate(detections):
        detections[idx]["score"] = float(pose_scores_np[idx])
        detections[idx]["R"] = list(pred_rot[idx].tolist())
        detections[idx]["t"] = list(pred_trans[idx].tolist())

    result_json = osp.join(f"{cfg.output_dir}/sam6d_results", "detection_pem.json")
    with open(result_json, "w", encoding="utf-8") as f:
        json.dump(detections, f)

    vis_path: Optional[str] = None
    if save_visualization:
        _log("=> visualizating ...")
        vis_path = osp.join(f"{cfg.output_dir}/sam6d_results", "vis_pem.png")
        valid_masks = pose_scores_np == pose_scores_np.max()
        K = input_data["K"].detach().cpu().numpy()[valid_masks]
        vis_img = visualize(
            img,
            pred_rot[valid_masks],
            pred_trans[valid_masks],
            model_points * 1000,
            K,
            vis_path,
        )
        vis_img.save(vis_path)

    best_idx = int(np.argmax(pose_scores_np))
    return {
        "detections": detections,
        "detection_pem_path": result_json,
        "vis_pem_path": vis_path,
        "pose_scores": pose_scores_np,
        "pred_R": pred_rot,
        "pred_t": pred_trans,
        "best_idx": best_idx,
        "best_detection": detections[best_idx],
    }


def pem_inference():
    """CLI: parse ``sys.argv`` and run PEM."""
    args = get_parser()
    run_pose_inference(
        args.output_dir,
        args.cad_path,
        args.rgb_path,
        args.depth_path,
        args.cam_path,
        args.seg_path,
        det_score_thresh=float(args.det_score_thresh),
        gpus=args.gpus,
        model_name=args.model,
        config_path=(
            args.config if osp.isabs(args.config) else osp.join(BASE_DIR, args.config)
        ),
        iter_=args.iter,
        exp_id=args.exp_id,
    )


if __name__ == "__main__":
    pem_inference()